# Generated by Django 4.2.11 on 2025-04-05 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
